// gpio - extracted from engine-peripherals.js

import { PeripheralType} from "./enums.js";

export let GpioSignalDefs = {
    GPIO: "GPIO",
    U0TXD: {
      name: "U0TXD",
      peripheral: PeripheralType.UART,
      index: 0,
      signal: "rsaReg26",
    },
    U0RXD: {
      name: "U0RXD",
      peripheral: PeripheralType.UART,
      index: 0,
      signal: "rsaReg57",
    },
    U0RTS: {
      name: "U0RTS",
      peripheral: PeripheralType.UART,
      index: 0,
      signal: "RTS",
    },
    U0CTS: {
      name: "U0CTS",
      peripheral: PeripheralType.UART,
      index: 0,
      signal: "CTS",
    },
    U0DSR: {
      name: "U0DSR",
      peripheral: PeripheralType.UART,
      index: 0,
      signal: "DSR",
    },
    U0DTR: {
      name: "U0DTR",
      peripheral: PeripheralType.UART,
      index: 0,
      signal: "DTR",
    },
    U1TXD: {
      name: "U1TXD",
      peripheral: PeripheralType.UART,
      index: 1,
      signal: "rsaReg26",
    },
    U1RXD: {
      name: "U1RXD",
      peripheral: PeripheralType.UART,
      index: 1,
      signal: "rsaReg57",
    },
    U1RTS: {
      name: "U1RTS",
      peripheral: PeripheralType.UART,
      index: 1,
      signal: "RTS",
    },
    U1CTS: {
      name: "U1CTS",
      peripheral: PeripheralType.UART,
      index: 1,
      signal: "CTS",
    },
    U1DSR: {
      name: "U1DSR",
      peripheral: PeripheralType.UART,
      index: 1,
      signal: "DSR",
    },
    U1DTR: {
      name: "U1DTR",
      peripheral: PeripheralType.UART,
      index: 1,
      signal: "DTR",
    },
    U2TXD: {
      name: "U2TXD",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "rsaReg26",
    },
    U2RXD: {
      name: "U2RXD",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "rsaReg57",
    },
    U2RTS: {
      name: "U2RTS",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "RTS",
    },
    U2CTS: {
      name: "U2CTS",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "CTS",
    },
    U2DSR: {
      name: "U2DSR",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "DSR",
    },
    U2DTR: {
      name: "U2DTR",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "DTR",
    },
    U3TXD: {
      name: "U3TXD",
      peripheral: PeripheralType.UART,
      index: 3,
      signal: "rsaReg26",
    },
    U3RXD: {
      name: "U3RXD",
      peripheral: PeripheralType.UART,
      index: 3,
      signal: "rsaReg57",
    },
    U3RTS: {
      name: "U3RTS",
      peripheral: PeripheralType.UART,
      index: 3,
      signal: "RTS",
    },
    U3CTS: {
      name: "U3CTS",
      peripheral: PeripheralType.UART,
      index: 3,
      signal: "CTS",
    },
    U3DSR: {
      name: "U3DSR",
      peripheral: PeripheralType.UART,
      index: 3,
      signal: "DSR",
    },
    U3DTR: {
      name: "U3DTR",
      peripheral: PeripheralType.UART,
      index: 3,
      signal: "DTR",
    },
    U4TXD: {
      name: "U4TXD",
      peripheral: PeripheralType.UART,
      index: 4,
      signal: "rsaReg26",
    },
    U4RXD: {
      name: "U4RXD",
      peripheral: PeripheralType.UART,
      index: 4,
      signal: "rsaReg57",
    },
    U4RTS: {
      name: "U4RTS",
      peripheral: PeripheralType.UART,
      index: 4,
      signal: "RTS",
    },
    U4CTS: {
      name: "U4CTS",
      peripheral: PeripheralType.UART,
      index: 4,
      signal: "CTS",
    },
    U4DSR: {
      name: "U4DSR",
      peripheral: PeripheralType.UART,
      index: 4,
      signal: "DSR",
    },
    U4DTR: {
      name: "U4DTR",
      peripheral: PeripheralType.UART,
      index: 4,
      signal: "DTR",
    },
    I2CEXT0_SCL: {
      name: "I2CEXT0_SCL",
      peripheral: PeripheralType.I2C,
      index: 0,
      signal: "SCL",
    },
    I2CEXT0_SDA: {
      name: "I2CEXT0_SDA",
      peripheral: PeripheralType.I2C,
      index: 0,
      signal: "SDA",
    },
    I2CEXT1_SCL: {
      name: "I2CEXT1_SCL",
      peripheral: PeripheralType.I2C,
      index: 1,
      signal: "SCL",
    },
    I2CEXT1_SDA: {
      name: "I2CEXT1_SDA",
      peripheral: PeripheralType.I2C,
      index: 1,
      signal: "SDA",
    },
    SPICS0: {
      name: "SPICS0",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "CS0",
    },
    SPICS1: {
      name: "SPICS1",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "CS1",
    },
    SPICS2: {
      name: "SPICS2",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "CS2",
    },
    SPID: {
      name: "SPID",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "MOSI",
    },
    SPICLK: {
      name: "SPICLK",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "CLK",
    },
    SPIQ: {
      name: "SPIQ",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "MISO",
    },
    SPIHD: {
      name: "SPIHD",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "HD",
    },
    SPIWP: {
      name: "SPIWP",
      peripheral: PeripheralType.SPI,
      index: 1,
      signal: "WP",
    },
    FSPICS0: {
      name: "FSPICS0",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS0",
    },
    FSPICS1: {
      name: "FSPICS1",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS1",
    },
    FSPICS2: {
      name: "FSPICS2",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS2",
    },
    FSPICS3: {
      name: "FSPICS3",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS3",
    },
    FSPICS4: {
      name: "FSPICS4",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS4",
    },
    FSPICS5: {
      name: "FSPICS5",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS5",
    },
    FSPID: {
      name: "FSPID",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "MOSI",
    },
    FSPICLK: {
      name: "FSPICLK",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CLK",
    },
    FSPIQ: {
      name: "FSPIQ",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "MISO",
    },
    FSPIHD: {
      name: "FSPIHD",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "HD",
    },
    FSPIWP: {
      name: "FSPIWP",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "WP",
    },
    FSPID4: {
      name: "FSPID4",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "D4",
    },
    FSPID5: {
      name: "FSPID5",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "D5",
    },
    FSPID6: {
      name: "FSPID6",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "D6",
    },
    FSPID7: {
      name: "FSPID7",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "D7",
    },
    FSPIDQS: {
      name: "FSPIDQS",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "DQS",
    },
    SPI3CS0: {
      name: "SPI3CS0",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS0",
    },
    SPI3CS1: {
      name: "SPI3CS1",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS1",
    },
    SPI3CS2: {
      name: "SPI3CS2",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS2",
    },
    SPI3CS3: {
      name: "SPI3CS3",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS3",
    },
    SPI3CS4: {
      name: "SPI3CS4",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS4",
    },
    SPI3CS5: {
      name: "SPI3CS5",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS5",
    },
    SPI3D: {
      name: "SPI3D",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "MOSI",
    },
    SPI3CLK: {
      name: "SPI3CLK",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CLK",
    },
    SPI3Q: {
      name: "SPI3Q",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "MISO",
    },
    SPI3HD: {
      name: "SPI3HD",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "HD",
    },
    SPI3WP: {
      name: "SPI3WP",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "WP",
    },
    HSPICS0: {
      name: "HSPICS0",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS0",
    },
    HSPICS1: {
      name: "HSPICS1",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS1",
    },
    HSPICS2: {
      name: "HSPICS2",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CS2",
    },
    HSPID: {
      name: "HSPID",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "MOSI",
    },
    HSPICLK: {
      name: "HSPICLK",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "CLK",
    },
    HSPIQ: {
      name: "HSPIQ",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "MISO",
    },
    HSPIHD: {
      name: "HSPIHD",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "HD",
    },
    HSPIWP: {
      name: "HSPIWP",
      peripheral: PeripheralType.SPI,
      index: 2,
      signal: "WP",
    },
    VSPICS0: {
      name: "VSPICS0",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS0",
    },
    VSPICS1: {
      name: "VSPICS1",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS1",
    },
    VSPICS2: {
      name: "VSPICS2",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS2",
    },
    VSPID: {
      name: "VSPID",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "MOSI",
    },
    VSPICLK: {
      name: "VSPICLK",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CLK",
    },
    VSPIQ: {
      name: "VSPIQ",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "MISO",
    },
    VSPIHD: {
      name: "VSPIHD",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "HD",
    },
    VSPIWP: {
      name: "VSPIWP",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "WP",
    },
    LP_UART_RXD: {
      name: "LP_UART_RXD",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "rsaReg57",
    },
    LP_UART_TXD: {
      name: "LP_UART_TXD",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "rsaReg26",
    },
    LP_UART_RTS: {
      name: "LP_UART_RTS",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "RTS",
    },
    LP_UART_CTS: {
      name: "LP_UART_CTS",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "CTS",
    },
    LP_UART_DSR: {
      name: "LP_UART_DSR",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "DSR",
    },
    LP_UART_DTR: {
      name: "LP_UART_DTR",
      peripheral: PeripheralType.UART,
      index: 2,
      signal: "DTR",
    },
    LP_I2C_SDA: {
      name: "LP_I2C_SDA",
      peripheral: PeripheralType.I2C,
      index: 1,
      signal: "SDA",
    },
    LP_I2C_SCL: {
      name: "LP_I2C_SCL",
      peripheral: PeripheralType.I2C,
      index: 1,
      signal: "SCL",
    },
    LP_SPI_CS0: {
      name: "LP_SPI_CS0",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CS0",
    },
    LP_SPI_D: {
      name: "LP_SPI_D",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "MOSI",
    },
    LP_SPI_CLK: {
      name: "LP_SPI_CLK",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "CLK",
    },
    LP_SPI_Q: {
      name: "LP_SPI_Q",
      peripheral: PeripheralType.SPI,
      index: 3,
      signal: "MISO",
    },
    PCNT_SIG_CH0_IN0: {
      name: "PCNT_SIG_CH0_IN0",
      peripheral: PeripheralType.PCNT,
      index: 0,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN0: {
      name: "PCNT_SIG_CH1_IN0",
      peripheral: PeripheralType.PCNT,
      index: 0,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN0: {
      name: "PCNT_CTRL_CH0_IN0",
      peripheral: PeripheralType.PCNT,
      index: 0,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN0: {
      name: "PCNT_CTRL_CH1_IN0",
      peripheral: PeripheralType.PCNT,
      index: 0,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN1: {
      name: "PCNT_SIG_CH0_IN1",
      peripheral: PeripheralType.PCNT,
      index: 1,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN1: {
      name: "PCNT_SIG_CH1_IN1",
      peripheral: PeripheralType.PCNT,
      index: 1,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN1: {
      name: "PCNT_CTRL_CH0_IN1",
      peripheral: PeripheralType.PCNT,
      index: 1,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN1: {
      name: "PCNT_CTRL_CH1_IN1",
      peripheral: PeripheralType.PCNT,
      index: 1,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN2: {
      name: "PCNT_SIG_CH0_IN2",
      peripheral: PeripheralType.PCNT,
      index: 2,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN2: {
      name: "PCNT_SIG_CH1_IN2",
      peripheral: PeripheralType.PCNT,
      index: 2,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN2: {
      name: "PCNT_CTRL_CH0_IN2",
      peripheral: PeripheralType.PCNT,
      index: 2,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN2: {
      name: "PCNT_CTRL_CH1_IN2",
      peripheral: PeripheralType.PCNT,
      index: 2,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN3: {
      name: "PCNT_SIG_CH0_IN3",
      peripheral: PeripheralType.PCNT,
      index: 3,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN3: {
      name: "PCNT_SIG_CH1_IN3",
      peripheral: PeripheralType.PCNT,
      index: 3,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN3: {
      name: "PCNT_CTRL_CH0_IN3",
      peripheral: PeripheralType.PCNT,
      index: 3,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN3: {
      name: "PCNT_CTRL_CH1_IN3",
      peripheral: PeripheralType.PCNT,
      index: 3,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN4: {
      name: "PCNT_SIG_CH0_IN4",
      peripheral: PeripheralType.PCNT,
      index: 4,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN4: {
      name: "PCNT_SIG_CH1_IN4",
      peripheral: PeripheralType.PCNT,
      index: 4,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN4: {
      name: "PCNT_CTRL_CH0_IN4",
      peripheral: PeripheralType.PCNT,
      index: 4,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN4: {
      name: "PCNT_CTRL_CH1_IN4",
      peripheral: PeripheralType.PCNT,
      index: 4,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN5: {
      name: "PCNT_SIG_CH0_IN5",
      peripheral: PeripheralType.PCNT,
      index: 5,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN5: {
      name: "PCNT_SIG_CH1_IN5",
      peripheral: PeripheralType.PCNT,
      index: 5,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN5: {
      name: "PCNT_CTRL_CH0_IN5",
      peripheral: PeripheralType.PCNT,
      index: 5,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN5: {
      name: "PCNT_CTRL_CH1_IN5",
      peripheral: PeripheralType.PCNT,
      index: 5,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN6: {
      name: "PCNT_SIG_CH0_IN6",
      peripheral: PeripheralType.PCNT,
      index: 6,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN6: {
      name: "PCNT_SIG_CH1_IN6",
      peripheral: PeripheralType.PCNT,
      index: 6,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN6: {
      name: "PCNT_CTRL_CH0_IN6",
      peripheral: PeripheralType.PCNT,
      index: 6,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN6: {
      name: "PCNT_CTRL_CH1_IN6",
      peripheral: PeripheralType.PCNT,
      index: 6,
      signal: "CTRL_CH1",
    },
    PCNT_SIG_CH0_IN7: {
      name: "PCNT_SIG_CH0_IN7",
      peripheral: PeripheralType.PCNT,
      index: 7,
      signal: "SIG_CH0",
    },
    PCNT_SIG_CH1_IN7: {
      name: "PCNT_SIG_CH1_IN7",
      peripheral: PeripheralType.PCNT,
      index: 7,
      signal: "SIG_CH1",
    },
    PCNT_CTRL_CH0_IN7: {
      name: "PCNT_CTRL_CH0_IN7",
      peripheral: PeripheralType.PCNT,
      index: 7,
      signal: "CTRL_CH0",
    },
    PCNT_CTRL_CH1_IN7: {
      name: "PCNT_CTRL_CH1_IN7",
      peripheral: PeripheralType.PCNT,
      index: 7,
      signal: "CTRL_CH1",
    },
    PCNT_RST_PAD_IN0: {
      name: "PCNT_RST_PAD_IN0",
      peripheral: PeripheralType.PCNT,
      index: 0,
      signal: "RST_PAD",
    },
    PCNT_RST_PAD_IN1: {
      name: "PCNT_RST_PAD_IN1",
      peripheral: PeripheralType.PCNT,
      index: 1,
      signal: "RST_PAD",
    },
    PCNT_RST_PAD_IN2: {
      name: "PCNT_RST_PAD_IN2",
      peripheral: PeripheralType.PCNT,
      index: 2,
      signal: "RST_PAD",
    },
    PCNT_RST_PAD_IN3: {
      name: "PCNT_RST_PAD_IN3",
      peripheral: PeripheralType.PCNT,
      index: 3,
      signal: "RST_PAD",
    },
    TWAI0_RX: {
      name: "TWAI0_RX",
      peripheral: PeripheralType.TWAI,
      index: 0,
      signal: "rsaReg57",
    },
    TWAI0_TX: {
      name: "TWAI0_TX",
      peripheral: PeripheralType.TWAI,
      index: 0,
      signal: "rsaReg26",
    },
    TWAI0_BUS_OFF_ON: {
      name: "TWAI0_BUS_OFF_ON",
      peripheral: PeripheralType.TWAI,
      index: 0,
      signal: "BUS_OFF_ON",
    },
    TWAI0_CLKOUT: {
      name: "TWAI0_CLKOUT",
      peripheral: PeripheralType.TWAI,
      index: 0,
      signal: "CLKOUT",
    },
    TWAI0_STANDBY: {
      name: "TWAI0_STANDBY",
      peripheral: PeripheralType.TWAI,
      index: 0,
      signal: "STANDBY",
    },
    TWAI1_RX: {
      name: "TWAI1_RX",
      peripheral: PeripheralType.TWAI,
      index: 1,
      signal: "rsaReg57",
    },
    TWAI1_TX: {
      name: "TWAI1_TX",
      peripheral: PeripheralType.TWAI,
      index: 1,
      signal: "rsaReg26",
    },
    TWAI1_BUS_OFF_ON: {
      name: "TWAI1_BUS_OFF_ON",
      peripheral: PeripheralType.TWAI,
      index: 1,
      signal: "BUS_OFF_ON",
    },
    TWAI1_CLKOUT: {
      name: "TWAI1_CLKOUT",
      peripheral: PeripheralType.TWAI,
      index: 1,
      signal: "CLKOUT",
    },
    TWAI1_STANDBY: {
      name: "TWAI1_STANDBY",
      peripheral: PeripheralType.TWAI,
      index: 1,
      signal: "STANDBY",
    },
    TWAI2_RX: {
      name: "TWAI2_RX",
      peripheral: PeripheralType.TWAI,
      index: 2,
      signal: "rsaReg57",
    },
    TWAI2_TX: {
      name: "TWAI2_TX",
      peripheral: PeripheralType.TWAI,
      index: 2,
      signal: "rsaReg26",
    },
    TWAI2_BUS_OFF_ON: {
      name: "TWAI2_BUS_OFF_ON",
      peripheral: PeripheralType.TWAI,
      index: 2,
      signal: "BUS_OFF_ON",
    },
    TWAI2_CLKOUT: {
      name: "TWAI2_CLKOUT",
      peripheral: PeripheralType.TWAI,
      index: 2,
      signal: "CLKOUT",
    },
    TWAI2_STANDBY: {
      name: "TWAI2_STANDBY",
      peripheral: PeripheralType.TWAI,
      index: 2,
      signal: "STANDBY",
    },
  };
