import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        Buffer: "readonly",
        performance: "readonly",
        crypto: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        AbortController: "readonly",
        SharedArrayBuffer: "readonly",
        Atomics: "readonly",
        Worker: "readonly",
        postMessage: "readonly",
        importScripts: "readonly",
        self: "readonly",
        globalThis: "readonly",
        webassembly: "readonly",
        WebAssembly: "readonly",
        WebSocket: "readonly",
        DataView: "readonly",
        ArrayBuffer: "readonly",
        Uint8Array: "readonly",
        Uint16Array: "readonly",
        Uint32Array: "readonly",
        Int8Array: "readonly",
        Int16Array: "readonly",
        Int32Array: "readonly",
        Float32Array: "readonly",
        Float64Array: "readonly",
        BigInt64Array: "readonly",
        BigUint64Array: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        Error: "readonly",
        RangeError: "readonly",
        TypeError: "readonly",
        SyntaxError: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        structuredClone: "readonly",
        fetch: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "no-undef": "error",
      "eqeqeq": ["warn", "smart"],
      "no-constant-condition": "warn",
      "no-debugger": "warn",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-redeclare": "error",
      "no-unreachable": "warn",
      "no-shadow-restricted-names": "error",
      "no-self-compare": "warn",
      "no-template-curly-in-string": "warn",
      "no-loss-of-precision": "warn",
      "no-unconditional-jump": "off",
    },
  },
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "src/engine/esp-xtensa/esp_engine_wasm.wasm",
      "tests/**",
      "bin/**",
      "build.mjs",
    ],
  },
];
