// xtensa - extracted from engine-peripherals.js

import { GpioSignalDefs } from "../common/gpio.js";

export const RegisterType = {
  PC: 0,
  AR: 0x1000000,
  Special: 0x2000000,
  User: 0x3000000,
  FP: 0x4000000,
  Mask: 0xff000000,
};
export let LoopBegin = 0,
  LoopEnd = 1,
  LoopCount = 2,
  ExcCause = 3,
  PsRegister = 4,
  SarRegister = 12,
  LbegRegister = 16,
  WindowStart = 17,
  InterruptState = 32,
  InterruptEnable = 33,
  InterruptClear = 34,
  InterruptSet = 35,
  MemFaultInfo = 72,
  CacheControl = 73,
  DdrRegister = 176,
  Eps2Register = 208,
  IntSet = 230,
  IntLevelAlias = 231,
  IntSetAlias = 230,
  IntStatusAlias = 232,
  IntRawAlias = 233,
  CcountAlias = 234,
  CcompareAlias = 235,
  Ccompare3Reg = 236;
export let XtensaRegisterTable = [
    RegisterType.PC,
    0 | RegisterType.AR,
    1 | RegisterType.AR,
    2 | RegisterType.AR,
    3 | RegisterType.AR,
    4 | RegisterType.AR,
    5 | RegisterType.AR,
    6 | RegisterType.AR,
    7 | RegisterType.AR,
    8 | RegisterType.AR,
    9 | RegisterType.AR,
    10 | RegisterType.AR,
    11 | RegisterType.AR,
    12 | RegisterType.AR,
    13 | RegisterType.AR,
    14 | RegisterType.AR,
    15 | RegisterType.AR,
    16 | RegisterType.AR,
    17 | RegisterType.AR,
    18 | RegisterType.AR,
    19 | RegisterType.AR,
    20 | RegisterType.AR,
    21 | RegisterType.AR,
    22 | RegisterType.AR,
    23 | RegisterType.AR,
    24 | RegisterType.AR,
    25 | RegisterType.AR,
    26 | RegisterType.AR,
    27 | RegisterType.AR,
    28 | RegisterType.AR,
    29 | RegisterType.AR,
    30 | RegisterType.AR,
    31 | RegisterType.AR,
    32 | RegisterType.AR,
    33 | RegisterType.AR,
    34 | RegisterType.AR,
    35 | RegisterType.AR,
    36 | RegisterType.AR,
    37 | RegisterType.AR,
    38 | RegisterType.AR,
    39 | RegisterType.AR,
    40 | RegisterType.AR,
    41 | RegisterType.AR,
    42 | RegisterType.AR,
    43 | RegisterType.AR,
    44 | RegisterType.AR,
    45 | RegisterType.AR,
    46 | RegisterType.AR,
    47 | RegisterType.AR,
    48 | RegisterType.AR,
    49 | RegisterType.AR,
    50 | RegisterType.AR,
    51 | RegisterType.AR,
    52 | RegisterType.AR,
    53 | RegisterType.AR,
    54 | RegisterType.AR,
    55 | RegisterType.AR,
    56 | RegisterType.AR,
    57 | RegisterType.AR,
    58 | RegisterType.AR,
    59 | RegisterType.AR,
    60 | RegisterType.AR,
    61 | RegisterType.AR,
    62 | RegisterType.AR,
    63 | RegisterType.AR,
    RegisterType.Special | LoopBegin,
    RegisterType.Special | LoopEnd,
    RegisterType.Special | LoopCount,
    RegisterType.Special | ExcCause,
    RegisterType.Special | MemFaultInfo,
    RegisterType.Special | CacheControl,
    RegisterType.Special | DdrRegister,
    RegisterType.Special | Eps2Register,
    RegisterType.Special | IntSet,
    RegisterType.User | IntLevelAlias,
    RegisterType.Special | PsRegister,
    RegisterType.Special | SarRegister,
    RegisterType.Special | LbegRegister,
    RegisterType.Special | WindowStart,
    RegisterType.Special | InterruptState,
    RegisterType.Special | InterruptEnable,
    RegisterType.Special | InterruptClear,
    RegisterType.Special | InterruptSet,
    RegisterType.User | IntSetAlias,
    RegisterType.User | CcountAlias,
    RegisterType.User | CcompareAlias,
    RegisterType.User | Ccompare3Reg,
    0 | RegisterType.FP,
    1 | RegisterType.FP,
    2 | RegisterType.FP,
    3 | RegisterType.FP,
    4 | RegisterType.FP,
    5 | RegisterType.FP,
    6 | RegisterType.FP,
    7 | RegisterType.FP,
    8 | RegisterType.FP,
    9 | RegisterType.FP,
    10 | RegisterType.FP,
    11 | RegisterType.FP,
    12 | RegisterType.FP,
    13 | RegisterType.FP,
    14 | RegisterType.FP,
    15 | RegisterType.FP,
    RegisterType.User | IntStatusAlias,
    RegisterType.User | IntRawAlias,
  ],
  GpioConstantPins = { CONST_ONE_INPUT: 56, CONST_ZERO_INPUT: 48 },
  {
    U0RXD: U0RXD,
    U0RTS: U0RTS,
    U0CTS: U0CTS,
    U0TXD: U0TXD,
    U0DTR: U0DTR,
    U0DSR: U0DSR,
  } = GpioSignalDefs,
  { U1RXD: U1RXD, U1RTS: U1RTS, U1CTS: U1CTS, U1TXD: U1TXD } = GpioSignalDefs,
  { U2RXD: U2RXD, U2RTS: U2RTS, U2CTS: U2CTS, U2TXD: U2TXD } = GpioSignalDefs,
  {
    I2CEXT0_SCL: I2CEXT0_SCL,
    I2CEXT0_SDA: I2CEXT0_SDA,
    I2CEXT1_SCL: I2CEXT1_SCL,
    I2CEXT1_SDA: I2CEXT1_SDA,
  } = GpioSignalDefs,
  {
    SPIQ: SPIQ,
    SPIHD: SPIHD,
    SPIWP: SPIWP,
    SPICLK: SPICLK,
    SPID: SPID,
    SPICS0: SPICS0,
    SPICS1: SPICS1,
    SPICS2: SPICS2,
  } = GpioSignalDefs,
  {
    HSPIQ: HSPIQ,
    HSPIHD: HSPIHD,
    HSPIWP: HSPIWP,
    HSPICLK: HSPICLK,
    HSPID: HSPID,
    HSPICS0: HSPICS0,
    HSPICS1: HSPICS1,
    HSPICS2: HSPICS2,
  } = GpioSignalDefs,
  {
    VSPIQ: VSPIQ,
    VSPIHD: VSPIHD,
    VSPIWP: VSPIWP,
    VSPICLK: VSPICLK,
    VSPID: VSPID,
    VSPICS0: VSPICS0,
    VSPICS1: VSPICS1,
    VSPICS2: VSPICS2,
  } = GpioSignalDefs,
  {
    TWAI0_RX: TWAI0_RX,
    TWAI0_TX: TWAI0_TX,
    TWAI0_BUS_OFF_ON: TWAI0_BUS_OFF_ON,
    TWAI0_CLKOUT: TWAI0_CLKOUT,
    TWAI0_STANDBY: TWAI0_STANDBY,
  } = GpioSignalDefs,
  Esp32GpioMatrixEntries = [
    { i: 0, in: SPICLK, out: SPICLK },
    { i: 1, in: SPIQ, out: SPIQ },
    { i: 2, in: SPID, out: SPID },
    { i: 3, in: SPIHD, out: SPIHD },
    { i: 4, in: SPIWP, out: SPIWP },
    { i: 5, in: SPICS0, out: SPICS0 },
    { i: 6, in: SPICS1, out: SPICS1 },
    { i: 7, in: SPICS2, out: SPICS2 },
    { i: 8, in: HSPICLK, out: HSPICLK },
    { i: 9, in: HSPIQ, out: HSPIQ },
    { i: 10, in: HSPID, out: HSPID },
    { i: 11, in: HSPICS0, out: HSPICS0 },
    { i: 12, in: HSPIHD, out: HSPIHD },
    { i: 13, in: HSPIWP, out: HSPIWP },
    { i: 14, in: U0RXD, out: U0TXD },
    { i: 15, in: U0CTS, out: U0RTS },
    { i: 16, in: U0DSR, out: U0DTR },
    { i: 17, in: U1RXD, out: U1TXD },
    { i: 18, in: U1CTS, out: U1RTS },
    { i: 23, in: "I2S0O_BCK_in", out: "I2S0O_BCK_out" },
    { i: 24, in: "I2S1O_BCK_in", out: "I2S1O_BCK_out" },
    { i: 25, in: "I2S0O_WS_in", out: "I2S0O_WS_out" },
    { i: 26, in: "I2S1O_WS_in", out: "I2S1O_WS_out" },
    { i: 27, in: "I2S0I_BCK_in", out: "I2S0I_BCK_out" },
    { i: 28, in: "I2S0I_WS_in", out: "I2S0I_WS_out" },
    { i: 29, in: I2CEXT0_SCL, out: I2CEXT0_SCL },
    { i: 30, in: I2CEXT0_SDA, out: I2CEXT0_SDA },
    { i: 31, in: "pwm0_sync0_in", out: "sdio_tohost_int_out" },
    { i: 32, in: "pwm0_sync1_in", out: "pwm0_out0a" },
    { i: 33, in: "pwm0_sync2_in", out: "pwm0_out0b" },
    { i: 34, in: "pwm0_f0_in", out: "pwm0_out1a" },
    { i: 35, in: "pwm0_f1_in", out: "pwm0_out1b" },
    { i: 36, in: "pwm0_f2_in", out: "pwm0_out2a" },
    { i: 37, in: null, out: "pwm0_out2b" },
    { i: 39, in: GpioSignalDefs.PCNT_SIG_CH0_IN0, out: null },
    { i: 40, in: GpioSignalDefs.PCNT_SIG_CH1_IN0, out: null },
    { i: 41, in: GpioSignalDefs.PCNT_CTRL_CH0_IN0, out: null },
    { i: 42, in: GpioSignalDefs.PCNT_CTRL_CH1_IN0, out: null },
    { i: 43, in: GpioSignalDefs.PCNT_SIG_CH0_IN1, out: null },
    { i: 44, in: GpioSignalDefs.PCNT_SIG_CH1_IN1, out: null },
    { i: 45, in: GpioSignalDefs.PCNT_CTRL_CH0_IN1, out: null },
    { i: 46, in: GpioSignalDefs.PCNT_CTRL_CH1_IN1, out: null },
    { i: 47, in: GpioSignalDefs.PCNT_SIG_CH0_IN2, out: null },
    { i: 48, in: GpioSignalDefs.PCNT_SIG_CH1_IN2, out: null },
    { i: 49, in: GpioSignalDefs.PCNT_CTRL_CH0_IN2, out: null },
    { i: 50, in: GpioSignalDefs.PCNT_CTRL_CH1_IN2, out: null },
    { i: 51, in: GpioSignalDefs.PCNT_SIG_CH0_IN3, out: null },
    { i: 52, in: GpioSignalDefs.PCNT_SIG_CH1_IN3, out: null },
    { i: 53, in: GpioSignalDefs.PCNT_CTRL_CH0_IN3, out: null },
    { i: 54, in: GpioSignalDefs.PCNT_CTRL_CH1_IN3, out: null },
    { i: 55, in: GpioSignalDefs.PCNT_SIG_CH0_IN4, out: null },
    { i: 56, in: GpioSignalDefs.PCNT_SIG_CH1_IN4, out: null },
    { i: 57, in: GpioSignalDefs.PCNT_CTRL_CH0_IN4, out: null },
    { i: 58, in: GpioSignalDefs.PCNT_CTRL_CH1_IN4, out: null },
    { i: 61, in: HSPICS1, out: HSPICS1 },
    { i: 62, in: HSPICS2, out: HSPICS2 },
    { i: 63, in: VSPICLK, out: VSPICLK },
    { i: 64, in: VSPIQ, out: VSPIQ },
    { i: 65, in: VSPID, out: VSPID },
    { i: 66, in: VSPIHD, out: VSPIHD },
    { i: 67, in: VSPIWP, out: VSPIWP },
    { i: 68, in: VSPICS0, out: VSPICS0 },
    { i: 69, in: VSPICS1, out: VSPICS1 },
    { i: 70, in: VSPICS2, out: VSPICS2 },
    { i: 71, in: GpioSignalDefs.PCNT_SIG_CH0_IN5, out: "ledc_hs_sig_out0" },
    { i: 72, in: GpioSignalDefs.PCNT_SIG_CH1_IN5, out: "ledc_hs_sig_out1" },
    { i: 73, in: GpioSignalDefs.PCNT_CTRL_CH0_IN5, out: "ledc_hs_sig_out2" },
    { i: 74, in: GpioSignalDefs.PCNT_CTRL_CH1_IN5, out: "ledc_hs_sig_out3" },
    { i: 75, in: GpioSignalDefs.PCNT_SIG_CH0_IN6, out: "ledc_hs_sig_out4" },
    { i: 76, in: GpioSignalDefs.PCNT_SIG_CH1_IN6, out: "ledc_hs_sig_out5" },
    { i: 77, in: GpioSignalDefs.PCNT_CTRL_CH0_IN6, out: "ledc_hs_sig_out6" },
    { i: 78, in: GpioSignalDefs.PCNT_CTRL_CH1_IN6, out: "ledc_hs_sig_out7" },
    { i: 79, in: GpioSignalDefs.PCNT_SIG_CH0_IN7, out: "ledc_ls_sig_out0" },
    { i: 80, in: GpioSignalDefs.PCNT_SIG_CH1_IN7, out: "ledc_ls_sig_out1" },
    { i: 81, in: GpioSignalDefs.PCNT_CTRL_CH0_IN7, out: "ledc_ls_sig_out2" },
    { i: 82, in: GpioSignalDefs.PCNT_CTRL_CH1_IN7, out: "ledc_ls_sig_out3" },
    { i: 83, in: "rmt_sig_in0", out: "ledc_ls_sig_out4" },
    { i: 84, in: "rmt_sig_in1", out: "ledc_ls_sig_out5" },
    { i: 85, in: "rmt_sig_in2", out: "ledc_ls_sig_out6" },
    { i: 86, in: "rmt_sig_in3", out: "ledc_ls_sig_out7" },
    { i: 87, in: "rmt_sig_in4", out: "rmt_sig_out0" },
    { i: 88, in: "rmt_sig_in5", out: "rmt_sig_out1" },
    { i: 89, in: "rmt_sig_in6", out: "rmt_sig_out2" },
    { i: 90, in: "rmt_sig_in7", out: "rmt_sig_out3" },
    { i: 91, in: null, out: "rmt_sig_out4" },
    { i: 92, in: null, out: "rmt_sig_out5" },
    { i: 93, in: null, out: "rmt_sig_out6" },
    { i: 94, in: TWAI0_RX, out: "rmt_sig_out7" },
    { i: 95, in: I2CEXT1_SCL, out: I2CEXT1_SCL },
    { i: 96, in: I2CEXT1_SDA, out: I2CEXT1_SDA },
    { i: 97, in: "host_card_detect_n_1", out: "host_ccmd_od_pullup_en_n" },
    { i: 98, in: "host_card_detect_n_2", out: "host_rst_n_1" },
    { i: 99, in: "host_card_write_prt_1", out: "host_rst_n_2" },
    { i: 100, in: "host_card_write_prt_2", out: "gpio_sd0_out" },
    { i: 101, in: "host_card_int_n_1", out: "gpio_sd1_out" },
    { i: 102, in: "host_card_int_n_2", out: "gpio_sd2_out" },
    { i: 103, in: "pwm1_sync0_in", out: "gpio_sd3_out" },
    { i: 104, in: "pwm1_sync1_in", out: "gpio_sd4_out" },
    { i: 105, in: "pwm1_sync2_in", out: "gpio_sd5_out" },
    { i: 106, in: "pwm1_f0_in", out: "gpio_sd6_out" },
    { i: 107, in: "pwm1_f1_in", out: "gpio_sd7_out" },
    { i: 108, in: "pwm1_f2_in", out: "pwm1_out0a" },
    { i: 109, in: "pwm0_cap0_in", out: "pwm1_out0b" },
    { i: 110, in: "pwm0_cap1_in", out: "pwm1_out1a" },
    { i: 111, in: "pwm0_cap2_in", out: "pwm1_out1b" },
    { i: 112, in: "pwm1_cap0_in", out: "pwm1_out2a" },
    { i: 113, in: "pwm1_cap1_in", out: "pwm1_out2b" },
    { i: 114, in: "pwm1_cap2_in", out: null },
    { i: 123, in: null, out: TWAI0_TX },
    { i: 124, in: null, out: TWAI0_BUS_OFF_ON },
    { i: 125, in: null, out: TWAI0_CLKOUT },
    { i: 140, in: "I2S0I_DATA_in0", out: "I2S0O_DATA_out0" },
    { i: 141, in: "I2S0I_DATA_in1", out: "I2S0O_DATA_out1" },
    { i: 142, in: "I2S0I_DATA_in2", out: "I2S0O_DATA_out2" },
    { i: 143, in: "I2S0I_DATA_in3", out: "I2S0O_DATA_out3" },
    { i: 144, in: "I2S0I_DATA_in4", out: "I2S0O_DATA_out4" },
    { i: 145, in: "I2S0I_DATA_in5", out: "I2S0O_DATA_out5" },
    { i: 146, in: "I2S0I_DATA_in6", out: "I2S0O_DATA_out6" },
    { i: 147, in: "I2S0I_DATA_in7", out: "I2S0O_DATA_out7" },
    { i: 148, in: "I2S0I_DATA_in8", out: "I2S0O_DATA_out8" },
    { i: 149, in: "I2S0I_DATA_in9", out: "I2S0O_DATA_out9" },
    { i: 150, in: "I2S0I_DATA_in10", out: "I2S0O_DATA_out10" },
    { i: 151, in: "I2S0I_DATA_in11", out: "I2S0O_DATA_out11" },
    { i: 152, in: "I2S0I_DATA_in12", out: "I2S0O_DATA_out12" },
    { i: 153, in: "I2S0I_DATA_in13", out: "I2S0O_DATA_out13" },
    { i: 154, in: "I2S0I_DATA_in14", out: "I2S0O_DATA_out14" },
    { i: 155, in: "I2S0I_DATA_in15", out: "I2S0O_DATA_out15" },
    { i: 156, in: null, out: "I2S0O_DATA_out16" },
    { i: 157, in: null, out: "I2S0O_DATA_out17" },
    { i: 158, in: null, out: "I2S0O_DATA_out18" },
    { i: 159, in: null, out: "I2S0O_DATA_out19" },
    { i: 160, in: null, out: "I2S0O_DATA_out20" },
    { i: 161, in: null, out: "I2S0O_DATA_out21" },
    { i: 162, in: null, out: "I2S0O_DATA_out22" },
    { i: 163, in: null, out: "I2S0O_DATA_out23" },
    { i: 164, in: "I2S1I_BCK_in", out: "I2S1I_BCK_out" },
    { i: 165, in: "I2S1I_WS_in", out: "I2S1I_WS_out" },
    { i: 166, in: "I2S1I_DATA_in0", out: "I2S1O_DATA_out0" },
    { i: 167, in: "I2S1I_DATA_in1", out: "I2S1O_DATA_out1" },
    { i: 168, in: "I2S1I_DATA_in2", out: "I2S1O_DATA_out2" },
    { i: 169, in: "I2S1I_DATA_in3", out: "I2S1O_DATA_out3" },
    { i: 170, in: "I2S1I_DATA_in4", out: "I2S1O_DATA_out4" },
    { i: 171, in: "I2S1I_DATA_in5", out: "I2S1O_DATA_out5" },
    { i: 172, in: "I2S1I_DATA_in6", out: "I2S1O_DATA_out6" },
    { i: 173, in: "I2S1I_DATA_in7", out: "I2S1O_DATA_out7" },
    { i: 174, in: "I2S1I_DATA_in8", out: "I2S1O_DATA_out8" },
    { i: 175, in: "I2S1I_DATA_in9", out: "I2S1O_DATA_out9" },
    { i: 176, in: "I2S1I_DATA_in10", out: "I2S1O_DATA_out10" },
    { i: 177, in: "I2S1I_DATA_in11", out: "I2S1O_DATA_out11" },
    { i: 178, in: "I2S1I_DATA_in12", out: "I2S1O_DATA_out12" },
    { i: 179, in: "I2S1I_DATA_in13", out: "I2S1O_DATA_out13" },
    { i: 180, in: "I2S1I_DATA_in14", out: "I2S1O_DATA_out14" },
    { i: 181, in: "I2S1I_DATA_in15", out: "I2S1O_DATA_out15" },
    { i: 182, in: null, out: "I2S1O_DATA_out16" },
    { i: 183, in: null, out: "I2S1O_DATA_out17" },
    { i: 184, in: null, out: "I2S1O_DATA_out18" },
    { i: 185, in: null, out: "I2S1O_DATA_out19" },
    { i: 186, in: null, out: "I2S1O_DATA_out20" },
    { i: 187, in: null, out: "I2S1O_DATA_out21" },
    { i: 188, in: null, out: "I2S1O_DATA_out22" },
    { i: 189, in: null, out: "I2S1O_DATA_out23" },
    { i: 190, in: "I2S0I_H_SYNC", out: null },
    { i: 191, in: "I2S0I_V_SYNC", out: null },
    { i: 192, in: "I2S0I_H_ENABLE", out: null },
    { i: 193, in: "I2S1I_H_SYNC", out: null },
    { i: 194, in: "I2S1I_V_SYNC", out: null },
    { i: 195, in: "I2S1I_H_ENABLE", out: null },
    { i: 198, in: U2RXD, out: U2TXD },
    { i: 199, in: U2CTS, out: U2RTS },
    { i: 200, in: "emac_mdc_i", out: "emac_mdc_o" },
    { i: 201, in: "emac_mdi_i", out: "emac_mdo_o" },
    { i: 202, in: "emac_crs_i", out: "emac_crs_o" },
    { i: 203, in: "emac_col_i", out: "emac_col_o" },
    { i: 204, in: "pcmfsync_in", out: "bt_audio0_irq" },
    { i: 205, in: "pcmclk_in", out: "bt_audio1_irq" },
    { i: 206, in: "pcmdin", out: "bt_audio2_irq" },
    { i: 207, in: null, out: "ble_audio0_irq" },
    { i: 208, in: null, out: "ble_audio1_irq" },
    { i: 209, in: null, out: "ble_audio2_irq" },
    { i: 210, in: null, out: "pcmfsync_out" },
    { i: 211, in: null, out: "pcmclk_out" },
    { i: 212, in: null, out: "pcmdout" },
    { i: 213, in: null, out: "ble_audio_sync0_p" },
    { i: 214, in: null, out: "ble_audio_sync1_p" },
    { i: 215, in: null, out: "ble_audio_sync2_p" },
    { i: 224, in: null, out: "sig_in_func224" },
    { i: 225, in: null, out: "sig_in_func225" },
    { i: 226, in: null, out: "sig_in_func226" },
    { i: 227, in: null, out: "sig_in_func227" },
    { i: 228, in: null, out: "sig_in_func228" },
  ];


